# Generated by Django 5.1 on 2024-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_students_groupclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='courses.students'),
        ),
    ]
