# Generated by Django 5.1 on 2024-08-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_groupclass_max_students_groupclass_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
