# Generated by Django 5.1 on 2024-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_groupclass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='code',
            field=models.CharField(blank=True, default=2, max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
